# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    operator.array.age:
        class: AppBundle\Spec\Operator\ArrayAgeOperator
        tags:
            - { name: rulerz.operator, executor: rulerz.executor.array, operator: age }
    operator.doctrine.age:
        class: AppBundle\Spec\Operator\DoctrineAgeOperator
        tags:
            - { name: rulerz.operator, executor: rulerz.executor.doctrine, operator: age, inline: true }

    app.unicorn_repository:
        class: AppBundle\Repository\UnicornRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments:
            - 'AppBundle:Unicorn'
        calls:
            - [ setRulerZ, [ '@rulerz' ] ]
